spring:
  profiles:
    active: local
  jpa:
    generate-ddl: false
    database: MYSQL
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://dbdevplay.cjvrptolo3rh.ap-northeast-2.rds.amazonaws.com:3306/devplay?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false
    username: awsuser
    password: 'awsuserpassword'
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  tomcat:
    additional-tld-skip-patterns: '*.jar'
  port: '8080'

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
